/** Fieldmark brand tokens — see project brand guide */

export const BRAND = {
  name: "Fieldmark",
  tagline: "Know your margins before March.",

  colors: {
    teal: "#0D8B8B",
    tealHover: "#0A7474",
    charcoal: "#4A4A4A",
    cream: "#F5F3F0",
    gold: "#D4A574",
    alert: "#C0392B",
    success: "#27AE60",
    white: "#FFFFFF",
    grayLight: "#F0EEEB",
    grayMedium: "#9B9B9B",
    grayDark: "#2C2C2C",
    inputBorder: "#D4D0CB",
    alertBg: "#FFF8F0",
    dangerBg: "#FFF5F5",
    successBg: "#E8F8EF",
    tealMutedBg: "#E8F4F4"
  },

  fonts: {
    display: '"Montserrat", system-ui, sans-serif',
    body: '"Lato", system-ui, sans-serif'
  },

  radius: {
    sm: "8px",
    md: "12px",
    pill: "24px",
    full: "9999px"
  },

  shadow: {
    card: "0 2px 8px rgba(0, 0, 0, 0.06)",
    cardHighlight: "0 2px 12px rgba(13, 139, 139, 0.08)"
  },

  attribution: {
    benchmark:
      "Benchmarks sourced from University of Missouri Extension 2026 crop planning budgets (g651, g654).",
    dale:
      "Dale's analysis is generated by AI using your farm data and MU Extension benchmarks. For planning purposes only. Not financial advice."
  }
};

export const LOGO_SRC = "/images/fieldmark-logo.png";
